### ISSUE TITLE
Set-LoggingToArray won't create the overrides if OverrideMP doesn't exist

### ISSUE THREAD

**Issue by Cyr-Az** [PureStorage-OpenConnect/FlashArray-SCOM-Scripts#1]
Hi,

Quick issue : 
When you run Set-LoggingToArray for the first time with an Override MP name that doesn't exist yet, the Override MP will be created but the subsequent creation of overrides will fail.
I believe this happens because the $overrides_mp variable is not set in the following block after calling CreateManagementPack function  : 
```powershell  
    if (!$overrides_mp) {
        Write-Host "Creating management pack $OverridesManagementPackName..."
        CreateManagementPack -Name $OverridesManagementPackName
    }
```

**Comment by mikenelson-io** [comment]
Checking into this.

**Comment by mikenelson-io** [comment]
Code changes submitted for review.

**Comment by mikenelson-io** [comment]
Code being released after final signoff.
